### ISSUE TITLE
Create secret token on GKE for fabric8-ui team

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-build-team#11]
As req by ibrahim the fabric8-planner team needs to have a secrets token on GKE to communicate with fabric8-wit.

Internal Req [here ](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1009)

**Comment by jaseemabid** [comment]
As of now,

1. Since the images are ephemeral, cant just login through the Jenkins UI and add a credential. It will just get removed with next release. Also immutable infra ftw. 🤘 

2. Such secrets are visible to everyone, so not a good solution in a multi-tenant situation anyway.

This is a good case for adding proper credentials support to osio and moving this to tenant pipelines. Should probably be a sub task of osio on osio.

**Comment by rupalibehera** [comment]
@chmouel @jarifibrahim , closing this and the token was tested in this PR https://github.com/fabric8-ui/fabric8-planner/pull/2472
and I have merged changes required to pipeline librabry https://github.com/fabric8io/fabric8-pipeline-library/pull/382
