### ISSUE TITLE
Deprecating GKE

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-build-team#19]
Investigate GKE deprecation

**Comment by kbsingh** [comment]
Has this work been scoped up as yet ?

**Comment by pradeepto** [comment]
This relates to https://github.com/openshiftio/openshift.io/issues/1902

**Comment by pradeepto** [comment]
This relates to https://github.com/openshiftio/openshift.io/issues/1902

**Comment by jaseemabid** [comment]
### New jenkins server instead of migrating

Is it a good idea to _NOT_ migrate the current test.cd.fabric8.io to SD infra but start a new Jenkins server?
I have a feeling that the effort might be more than what can be justified. 

1. Most of the jobs are useless crap.
2. We need to only move what we need, and that might not be more than 10 or 20
3. We *MUST* script it from Ansible or something from the beginning
4. Setup automatic deployment from master or something so that its painless
5. The configuration of a ton of current jobs makes no sense - builds some branches but not others
6. There are wired crap like splitting all jobs into different folders like
   https://jenkins.cd.test.fabric8.io/job/fabric8io/
   https://jenkins.cd.test.fabric8.io/job/fabric8_CI/
   https://jenkins.cd.test.fabric8.io/job/fabric8io-auto-rel/
   for which I see no good reason
7. Make configuration available publicly

**Comment by chmouel** [comment]
The plan wasn't to do a full migration of all the jobs and thing we won't need.

If we have to move somewhere else we would do some cleanup including scripting Idempotente deployment methods and such, including the backups and whatnot.

This is not the part that get me worried to scope out, the part that get me worried for this sprint to figure out is the unknown external system that relies on the jenkins.test.cd URL  or relying on the the buggy jobs we have. None of us has insight about this, and it's hard to figure out,

**Comment by rupalibehera** [comment]
https://docs.google.com/spreadsheets/d/1XhRid--LBTtkaOLeZL9B6VULfpraWlgNopGbPl6-3kg/ in progress documenting

**Comment by sthaha** [comment]
Closing this since the epic has been moved to Planner
