### ISSUE TITLE
Investigate and understand what the 'container' blocks do

### ISSUE THREAD

**Issue by jaseemabid** [fabric8io/fabric8-build-team#20]
Not sure what `containers(ui)` blocks in the Jenkinsfile do and which plugin provides the functionality. 

@rupalibehera wasn't sure either so we need to dig into this and document it on the wiki.

**Comment by jaseemabid** [comment]
https://github.com/jenkinsci/kubernetes-plugin#pipeline-support

**Comment by pranavgore09** [comment]
thanks, @jaseemabid, because of that I could figure out configuration for `UI` container that planner Jenkins file is using extensively is coming from -
[this](https://github.com/fabric8-ui/fabric8-planner/blob/master/Jenkinsfile#L14) line invokes the call in pipeline codebase 
That invocation sets up configuration for UI container [here](https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/fabric8UITemplate.groovy#L28)  (and such other places in same file)

Thanks again!

**Comment by jaseemabid** [comment]
@pranavgore09 Your observation looks right. Yes, this is more convoluted than it should be. And we need docs.

**Comment by pradeepto** [comment]
Closing as obsolete.
